import { protos } from "@googlemaps/places";

export class GoogleRestaurant {
  constructor(
    readonly id: string,
    readonly name: string,
    readonly types: string[],
    readonly nationalPhoneNumber: string,
    readonly internationalPhoneNumber: string,
    readonly formattedAddress: string,
    readonly addressComponents: protos.google.maps.places.v1.Place.IAddressComponent[],
    readonly location: protos.google.type.ILatLng,
    readonly viewport: protos.google.geo.type.IViewport,
    readonly rating: number,
    readonly googleMapsUri: string,
    readonly websiteUri: string,
    readonly regularOpeningHours: protos.google.maps.places.v1.Place.IOpeningHours,
    readonly utcOffsetMinutes: number,
    readonly adrFormatAddress: string,
    readonly businessStatus: (protos.google.maps.places.v1.Place.BusinessStatus | keyof typeof protos.google.maps.places.v1.Place.BusinessStatus | null),
    readonly priceLevel: (protos.google.maps.places.v1.PriceLevel | keyof typeof protos.google.maps.places.v1.PriceLevel | null),
    readonly userRatingCount: number,
    readonly iconMaskBaseUri: string,
    readonly iconBackgroundColor: string,
    readonly displayName: protos.google.type.ILocalizedText,
    readonly primaryTypeDisplayName: protos.google.type.ILocalizedText,
    readonly takeout: boolean,
    readonly delivery: boolean,
    readonly dineIn: boolean,
    readonly reservable: boolean,
    readonly servesBreakfast: boolean,
    readonly servesLunch: boolean,
    readonly servesDinner: boolean,
    readonly servesBeer: boolean,
    readonly servesWine: boolean,
    readonly servesBrunch: boolean,
    readonly servesVegetarianFood: boolean,
    readonly currentOpeningHours: protos.google.maps.places.v1.Place.IOpeningHours,
    readonly primaryType: string,
    readonly shortFormattedAddress: string,
    readonly photos: protos.google.maps.places.v1.IPhoto[],
    readonly raw: any) { }

    clone(): GoogleRestaurant {
      return new GoogleRestaurant(
        this.id,
        this.name,
        this.types,
        this.nationalPhoneNumber,
        this.internationalPhoneNumber,
        this.formattedAddress,
        this.addressComponents,
        this.location,
        this.viewport,
        this.rating,
        this.googleMapsUri,
        this.websiteUri,
        this.regularOpeningHours,
        this.utcOffsetMinutes,
        this.adrFormatAddress,
        this.businessStatus,
        this.priceLevel,
        this.userRatingCount,
        this.iconMaskBaseUri,
        this.iconBackgroundColor,
        this.displayName,
        this.primaryTypeDisplayName,
        this.takeout,
        this.delivery,
        this.dineIn,
        this.reservable,
        this.servesBreakfast,
        this.servesLunch,
        this.servesDinner,
        this.servesBeer,
        this.servesWine,
        this.servesBrunch,
        this.servesVegetarianFood,
        this.currentOpeningHours,
        this.primaryType,
        this.shortFormattedAddress,
        this.photos,
        this.raw
      );
    }
}
