import {
  Beef,
  Beer,
  Bike,
  Cake,
  Carrot,
  ChefHat,
  Coffee,
  Cookie,
  Croissant,
  Fish,
  Flame,
  Globe,
  Hamburger,
  IceCream,
  Pizza,
  Sandwich,
  ShoppingBag,
  Snail,
  Soup,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Wine,
  type LucideIcon
} from "lucide-react";

const RESTAURANT_ICONS: Record<string, LucideIcon> = {
  // --- Regional / Ethnic ---
  afghani: Globe,
  african: Globe,
  american: UtensilsCrossed,
  asian: UtensilsCrossed,
  brazilian: Beef,
  chinese: Cookie,
  french: Snail,
  greek: ChefHat,
  indian: Soup,
  indonesian: UtensilsCrossed,
  italian: Pizza,
  japanese: UtensilsCrossed,
  korean: UtensilsCrossed,
  lebanese: ChefHat,
  mediterranean: Fish,
  mexican: UtensilsCrossed,
  middle_eastern: ChefHat,
  spanish: UtensilsCrossed,
  thai: Soup,
  turkish: ChefHat,
  vietnamese: Soup,

  // --- Food Types ---
  barbecue: Flame,
  breakfast: Coffee,
  brunch: Croissant,
  buffet: Utensils,
  dessert: Cake,
  dessert_shop: IceCream,
  fast_food: Sandwich,
  fine_dining: Wine,
  hamburger: Sandwich,
  pizza: Pizza,
  ramen: Soup,
  seafood: Fish,
  steak_house: Beef,
  sushi: Fish,
  vegan: Carrot,
  vegetarian: Vegan,
  friture: Hamburger,

  // --- Venues / Service ---
  bar_and_grill: Beer,
  meal_delivery: Bike,
  meal_takeaway: ShoppingBag,
  pub: Beer,
  restaurant: Utensils,
};

export function findTagIcon(tag: string): LucideIcon | undefined {
  return RESTAURANT_ICONS[tag] || undefined;
}
